# Couple green candlesticks trap - Analytics

### Import Library

In [2]:
import os
from pathlib import Path
import numpy as np
import pandas as pd
import numpy as np
import pandas_ta as ta
import seaborn as sns
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [12, 6]
plt.rcParams['figure.dpi'] = 120
import warnings
warnings.filterwarnings('ignore')
from Couple_green_canndlesticks_trap import prepare_data

### Load Price Data

In [4]:
notebook_path = os.getcwd()
current_dir = Path(notebook_path)
csv_file = str(current_dir) + '/VN30F1M_5minutes.csv'
is_file = os.path.isfile(csv_file)
if is_file:
    dataset = pd.read_csv(csv_file, index_col='Date', parse_dates=True)
else:
    print('remote')
    dataset = pd.read_csv("https://raw.githubusercontent.com/zuongthaotn/vn-stock-data/main/VN30ps/VN30F1M_5minutes.csv", index_col='Date', parse_dates=True)

In [5]:
dataset

                       Open    High     Low   Close  Volume
Date
2018-08-13 09:00:00   943.5   943.6   942.9   943.1    1812
2018-08-13 09:05:00   943.1   943.5   942.9   943.3    1323
2018-08-13 09:10:00   943.2   943.3   942.6   943.1    1207
2018-08-13 09:15:00   943.1   943.1   942.3   942.6    1196
2018-08-13 09:20:00   942.6   943.7   942.4   943.7    1765
...                     ...     ...     ...     ...     ...
2025-11-04 14:10:00  1890.7  1891.0  1885.5  1887.3    5379
2025-11-04 14:15:00  1887.2  1899.0  1887.2  1898.5   13871
2025-11-04 14:20:00  1898.2  1907.7  1897.0  1904.2   16090
2025-11-04 14:25:00  1904.1  1907.4  1900.3  1902.7    9901
2025-11-04 14:45:00  1898.0  1898.0  1898.0  1898.0    6043

[91594 rows x 5 columns]

In [6]:
data = prepare_data(dataset)

In [7]:
data

,Open,High,Low,Close,Volume,open_s1,close_s1,high_s1,signal,is_trap
Date,,,,,,,,,,
2018-08-13 09:50:00,945.0,946.0,944.3,946.0,1213,944.5,945.0,945.2,True,True
2018-08-13 11:00:00,943.7,944.2,943.3,944.2,1477,943.2,943.7,944.1,True,False
2018-08-13 11:10:00,944.9,946.1,944.6,946.1,1643,944.2,945.0,945.3,True,False
2018-08-13 11:25:00,945.5,947.0,945.3,947.0,2045,945.3,945.5,946.0,True,False
2018-08-13 13:35:00,948.0,948.3,947.9,948.3,1278,947.0,948.0,948.1,True,False
...,...,...,...,...,...,...,...,...,...,...
2025-10-13 14:00:00,1987.8,1993.0,1987.0,1993.0,7161,1986.3,1988.4,1989.5,True,False
2025-10-14 10:30:00,2027.3,2034.6,2026.8,2034.6,9222,2025.5,2027.3,2028.7,True,True
2025-10-15 09:55:00,2027.5,2028.9,2025.6,2028.9,4980,2023.6,2027.2,2027.9,True,True
2025-10-21 09:30:00,1884.7,1892.1,1884.2,1892.1,6671,1883.6,1884.7,1889.7,True,False
2025-10-28 14:15:00,1911.4,1930.2,1908.6,1930.2,17478,1907.6,1911.4,1914.0,True,False

In [ ]:

test()

test